import {
  Accessibility,
  Plus,
  BookOpen,
  IdCard,
  BedDouble,
  Ban,
  Zap,
  BookMarked,
  CalendarDays,
  Calendar,
  Phone,
  ChevronLeft,
  ChevronRight,
  SprayCan,
  Construction,
  Pencil,
  Mail,
  AlertCircle,
  Heart,
  Users,
  History,
  Star as StarIcon,
  Loader2,
  Info,
  Layers,
  WashingMachine,
  LogIn,
  LogOut,
  Bell,
  User,
  UserX,
  UserSearch,
  Globe,
  AlertTriangle,
  Receipt,
  UtensilsCrossed,
  Search,
  Languages,
  LayoutDashboard,
  Wallet,
  Network,
  Settings,
  ShieldCheck,
  BarChart3,
  Percent,
  DoorOpen,
  Lock,
  Monitor,
  HelpCircle,
  Key,
  X,
  GripVertical,
  CheckCircle,
  CheckCheck,
  Sun,
  Moon,
  Truck,
  StickyNote,
  MailCheck,
  ImageIcon,
  Upload,
  Copy,
  ToggleLeft,
  ToggleRight,
  Eye,
  EyeOff,
  Trash2,
  Crown,
  ChevronDown,
  ChevronUp,
  Bold,
  Italic,
  Underline,
  List,
  ListOrdered,
  Link,
  Wifi,
  AirVent,
  Tv,
  Refrigerator,
  Wine,
  Shield,
  Bath,
  ShowerHead,
  Coffee,
  Sofa,
  Printer,
  FileDown,
  FileText,
  Send,
  MessageSquare,
  MessageCircle,
  CreditCard,
  Banknote,
  Building2,
  MapPin,
  Clock,
  CalendarCheck,
  Baby,
  Paperclip,
  Kanban,
  Table,
  ClipboardList,
  ArrowLeftRight,
  PlusCircle,
  Inbox,
  CheckCircle2,
  ListChecks,
  Hotel,
  CalendarX,
  Circle,
  Wrench,
  Camera,
  Repeat,
  type LucideProps,
} from "lucide-react"

interface IconProps {
  name: string
  filled?: boolean
  size?: "sm" | "md" | "lg" | "xl"
  className?: string
}

const sizeMap = {
  sm: 16,
  md: 20,
  lg: 24,
  xl: 32,
} as const

const ICON_MAP: Record<string, React.ComponentType<LucideProps>> = {
  accessible: Accessibility,
  add: Plus,
  auto_stories: BookOpen,
  badge: IdCard,
  bed: BedDouble,
  block: Ban,
  bolt: Zap,
  book_online: BookMarked,
  calendar_month: CalendarDays,
  calendar_today: Calendar,
  call: Phone,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  cleaning_services: SprayCan,
  construction: Construction,
  edit: Pencil,
  email: Mail,
  error: AlertCircle,
  favorite: Heart,
  group: Users,
  history: History,
  hotel_class: StarIcon,
  hourglass_empty: Loader2,
  info: Info,
  layers: Layers,
  local_laundry_service: WashingMachine,
  login: LogIn,
  logout: LogOut,
  mail: Mail,
  notifications: Bell,
  person: User,
  person_off: UserX,
  person_search: UserSearch,
  phone: Phone,
  priority_high: AlertTriangle,
  public: Globe,
  receipt_long: Receipt,
  restaurant: UtensilsCrossed,
  search: Search,
  star: StarIcon,
  translate: Languages,
  close: X,
  check_circle: CheckCircle,
  done_all: CheckCheck,
  key: Key,
  build: Construction,
  do_not_disturb: Ban,
  local_shipping: Truck,
  sticky_note_2: StickyNote,
  mark_email_read: MailCheck,
  dashboard: LayoutDashboard,
  payments: Wallet,
  hub: Network,
  settings: Settings,
  admin_panel_settings: ShieldCheck,
  bar_chart: BarChart3,
  percent: Percent,
  meeting_room: DoorOpen,
  lock: Lock,
  desk: Monitor,
  help: HelpCircle,
  light_mode: Sun,
  dark_mode: Moon,
  drag_indicator: GripVertical,
  image: ImageIcon,
  photo: ImageIcon,
  upload: Upload,
  copy: Copy,
  duplicate: Copy,
  toggle_on: ToggleRight,
  toggle_off: ToggleLeft,
  visibility: Eye,
  visibility_off: EyeOff,
  delete: Trash2,
  trash: Trash2,
  crown: Crown,
  expand_more: ChevronDown,
  expand_less: ChevronUp,
  format_bold: Bold,
  format_italic: Italic,
  format_underlined: Underline,
  format_list_bulleted: List,
  format_list_numbered: ListOrdered,
  link: Link,
  wifi: Wifi,
  ac_unit: AirVent,
  tv: Tv,
  kitchen: Refrigerator,
  local_bar: Wine,
  security: Shield,
  bathtub: Bath,
  shower: ShowerHead,
  coffee: Coffee,
  sofa: Sofa,
  print: Printer,
  printer: Printer,
  file_download: FileDown,
  download: FileDown,
  file_text: FileText,
  description: FileText,
  send: Send,
  message: MessageSquare,
  chat: MessageCircle,
  whatsapp: MessageCircle,
  credit_card: CreditCard,
  money: Banknote,
  cash: Banknote,
  building: Building2,
  location: MapPin,
  map_pin: MapPin,
  clock: Clock,
  schedule: Clock,
  calendar_check: CalendarCheck,
  event_available: CalendarCheck,
  baby: Baby,
  child_care: Baby,
  attach_file: Paperclip,
  attachment: Paperclip,
  view_column: Kanban,
  table_rows: Table,
  view_agenda: ClipboardList,
  sync_alt: ArrowLeftRight,
  swap_horiz: ArrowLeftRight,
  compare_arrows: ArrowLeftRight,
  add_circle: PlusCircle,
  verified_user: ShieldCheck,
  warning: AlertTriangle,
  inbox: Inbox,
  task_alt: CheckCircle2,
  checklist: ListChecks,
  hotel: Hotel,
  event_busy: CalendarX,
  radio_button_unchecked: Circle,
  engineering: Wrench,
  handyman: Wrench,
  photo_camera: Camera,
  camera_alt: Camera,
  repeat: Repeat,
}

export function Icon({ name, size = "md", className = "" }: IconProps) {
  const IconComponent = ICON_MAP[name]
  const px = sizeMap[size]

  if (!IconComponent) {
    return <span className={className} style={{ width: px, height: px }} />
  }

  return (
    <IconComponent
      size={px}
      strokeWidth={1.8}
      className={className}
      aria-hidden="true"
    />
  )
}
